In [1]:
# Import Necessary Packages
import leafmap
import pandas as pd
import geopandas as gpd

In [2]:
df = pd.read_json("https://a5c7zwf7e5.execute-api.ap-southeast-2.amazonaws.com/dev/offences?locationType=Lga&startDate=9-23-2025&locationName=Brisbane&endDate=09-30-2025&format=JSON")
df.head()

,Type,Date,Postcode,Area of Interest,ABS Meshblock
0,Other Theft (excl. Unlawful Entry),2025-09-23,4169,Brisbane,3.008264e+10
1,Other Theft (excl. Unlawful Entry),2025-09-23,4032,Brisbane,3.056366e+10
2,Other Theft (excl. Unlawful Entry),2025-09-23,4030,Brisbane,3.056250e+10
3,Other Theft (excl. Unlawful Entry),2025-09-23,4005,Brisbane,3.010096e+10
4,Other Property Damage,2025-09-23,4034,Brisbane,3.003911e+10

In [3]:
absgdf= gpd.read_file("./Data/ABS_Data/MB_2016_QLD.dbf")
absgdf.head(100)

,MB_CODE16,MB_CAT16,SA1_MAIN16,SA1_7DIG16,SA2_MAIN16,SA2_5DIG16,SA2_NAME16,SA3_CODE16,SA3_NAME16,SA4_CODE16,SA4_NAME16,GCC_CODE16,GCC_NAME16,STE_CODE16,STE_NAME16,AREASQKM16,geometry
0,30000009499,NOUSUALRESIDENCE,39999949999,3949999,399999499,39499,No usual address (Qld),39999,No usual address (Qld),399,No usual address (Qld),39499,No usual address (Qld),3,Queensland,0.0000,None
1,30000010000,Parkland,31802148912,3148912,318021489,31489,Townsville - South,31802,Townsville,318,Townsville,3RQLD,Rest of Qld,3,Queensland,0.0387,"POLYGON ((147.06415 -19.24665, 147.06417 -19.2..."
2,30000020000,Parkland,31802148912,3148912,318021489,31489,Townsville - South,31802,Townsville,318,Townsville,3RQLD,Rest of Qld,3,Queensland,0.0071,"POLYGON ((147.07147 -19.25762, 147.07141 -19.2..."
3,30000030000,Parkland,31802148912,3148912,318021489,31489,Townsville - South,31802,Townsville,318,Townsville,3RQLD,Rest of Qld,3,Queensland,0.0004,"POLYGON ((147.0615 -19.24606, 147.06146 -19.24..."
4,30000050000,Residential,31503140809,3140809,315031408,31408,Barcaldine - Blackall,31503,Outback - South,315,Queensland - Outback,3RQLD,Rest of Qld,3,Queensland,0.0432,"POLYGON ((145.24063 -22.97139, 145.24083 -22.9..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,30001090000,Primary Production,30605116626,3116626,306051166,31166,Atherton,30605,Tablelands (East) - Kuranda,306,Cairns,3RQLD,Rest of Qld,3,Queensland,2.7469,"POLYGON ((145.41963 -17.24612, 145.41732 -17.2..."
96,30001100000,Parkland,30605116612,3116612,306051166,31166,Atherton,30605,Tablelands (East) - Kuranda,306,Cairns,3RQLD,Rest of Qld,3,Queensland,0.3153,"POLYGON ((145.46816 -17.26612, 145.46826 -17.2..."
97,30001110000,Parkland,30605116626,3116626,306051166,31166,Atherton,30605,Tablelands (East) - Kuranda,306,Cairns,3RQLD,Rest of Qld,3,Queensland,13.5644,"POLYGON ((145.41963 -17.24612, 145.43426 -17.2..."
98,30001122000,Industrial,30605116614,3116614,306051166,31166,Atherton,30605,Tablelands (East) - Kuranda,306,Cairns,3RQLD,Rest of Qld,3,Queensland,0.3027,"POLYGON ((145.48214 -17.25732, 145.48119 -17.2..."
99,30001131000,Industrial,30605116613,3116613,306051166,31166,Atherton,30605,Tablelands (East) - Kuranda,306,Cairns,3RQLD,Rest of Qld,3,Queensland,0.0464,"POLYGON ((145.47658 -17.25442, 145.4765 -17.25..."

In [4]:
absgdf['longitude'] = absgdf["geometry"].centroid.x
absgdf['latitude'] = absgdf["geometry"].centroid.y
absgdf['MB_CODE16'] = absgdf['MB_CODE16'].astype(int)
print(absgdf["longitude"])
print(absgdf["latitude"])

0               NaN
1        147.063018
2        147.072146
3        147.061558
4        145.241845
            ...
69759           NaN
69760           NaN
69761           NaN
69762           NaN
69763           NaN
Name: longitude, Length: 69764, dtype: float64
0              NaN
1       -19.246690
2       -19.257614
3       -19.245964
4       -22.970668
           ...
69759          NaN
69760          NaN
69761          NaN
69762          NaN
69763          NaN
Name: latitude, Length: 69764, dtype: float64

In [5]:
absgdf.dtypes

MB_CODE16        int64
MB_CAT16        object
SA1_MAIN16      object
SA1_7DIG16      object
SA2_MAIN16      object
SA2_5DIG16      object
SA2_NAME16      object
SA3_CODE16      object
SA3_NAME16      object
SA4_CODE16      object
SA4_NAME16      object
GCC_CODE16      object
GCC_NAME16      object
STE_CODE16      object
STE_NAME16      object
AREASQKM16     float64
geometry      geometry
longitude      float64
latitude       float64
dtype: object

In [6]:
crimedf= pd.merge(df, absgdf, left_on="ABS Meshblock", right_on = "MB_CODE16", how = "inner") 

crimedf.tail()

,Type,Date,Postcode,Area of Interest,ABS Meshblock,MB_CODE16,MB_CAT16,SA1_MAIN16,SA1_7DIG16,SA2_MAIN16,...,SA4_CODE16,SA4_NAME16,GCC_CODE16,GCC_NAME16,STE_CODE16,STE_NAME16,AREASQKM16,geometry,longitude,latitude
2127,Unlawful Entry,2025-09-30 23:05:00,4069,Brisbane,3.010932e+10,30109320000,Residential,30402109105,3109105,304021091,...,304,Brisbane - West,3GBRI,Greater Brisbane,3,Queensland,0.4861,"POLYGON ((152.92031 -27.52263, 152.92015 -27.5...",152.916376,-27.519595
2128,Other Property Damage,2025-09-30 23:10:00,4014,Brisbane,3.056305e+10,30563054800,Residential,30203103916,3103916,302031039,...,302,Brisbane - North,3GBRI,Greater Brisbane,3,Queensland,0.0373,"POLYGON ((153.08404 -27.36495, 153.08416 -27.3...",153.084209,-27.366463
2129,Good Order Offences,2025-09-30 23:59:00,4053,Brisbane,3.012002e+10,30120021000,Industrial,30202103220,3103220,302021032,...,302,Brisbane - North,3GBRI,Greater Brisbane,3,Queensland,0.0308,"POLYGON ((153.01327 -27.41432, 153.0133 -27.41...",153.014799,-27.414855
2130,Other Theft (excl. Unlawful Entry),2025-09-30 23:59:00,4170,Brisbane,3.010269e+10,30102690000,Residential,30502111715,3111715,305021117,...,305,Brisbane Inner City,3GBRI,Greater Brisbane,3,Queensland,0.0238,"POLYGON ((153.07431 -27.48335, 153.07427 -27.4...",153.072537,-27.482753
2131,Other Theft (excl. Unlawful Entry),2025-09-30 23:59:00,4170,Brisbane,3.010269e+10,30102690000,Residential,30502111715,3111715,305021117,...,305,Brisbane Inner City,3GBRI,Greater Brisbane,3,Queensland,0.0238,"POLYGON ((153.07431 -27.48335, 153.07427 -27.4...",153.072537,-27.482753

In [7]:
crimedf2 = crimedf[["Type","Date","Postcode","longitude","latitude"]]
crimedf2.dtypes

Type                 object
Date         datetime64[ns]
Postcode              int64
longitude           float64
latitude            float64
dtype: object

In [8]:
Arson = crimedf2[crimedf2["Type"]=="Arson"].reset_index(drop=True)
Assault = crimedf2[crimedf2["Type"]=="Assault"].reset_index(drop=True)
Drugs = crimedf2[crimedf2["Type"]=="Drug Offences"].reset_index(drop=True)
Fraud = crimedf2[crimedf2["Type"]=="Fraud"].reset_index(drop=True)
Gaming = crimedf2[crimedf2["Type"]=="Gaming Racing & Betting Offences"].reset_index(drop=True)
GoodOrder = crimedf2[crimedf2["Type"]=="Good Order Offences"].reset_index(drop=True)
Stolen = crimedf2[crimedf2["Type"]=="Handling Stolen Goods"].reset_index(drop=True)
Homicide = crimedf2[crimedf2["Type"]=="Homicide (Murder)"].reset_index(drop=True)
OtherHomicide = crimedf2[crimedf2["Type"]=="Other Homicide"].reset_index(drop=True)
Liquor = crimedf2[crimedf2["Type"]=="Liquor (excl. Drunkenness)"].reset_index(drop=True)
Misc = crimedf2[crimedf2["Type"]=="Miscellaneous Offences"].reset_index(drop=True)
Other = crimedf2[crimedf2["Type"]=="Other Offences Against the Person"].reset_index(drop=True)
Property = crimedf2[crimedf2["Type"]=="Other Property Damage"].reset_index(drop=True)
OtherTheft = crimedf2[crimedf2["Type"]=="Other Theft (excl. Unlawful Entry)"].reset_index(drop=True)
Prostitution = crimedf2[crimedf2["Type"]=="Prostitution Offences"].reset_index(drop=True)
Robbery = crimedf2[crimedf2["Type"]=="Robbery"].reset_index(drop=True)
Stock = crimedf2[crimedf2["Type"]=="Stock Related Offences"].reset_index(drop=True)
Traffic = crimedf2[crimedf2["Type"]=="Traffic and Related Offences"].reset_index(drop=True)
Trespassing = crimedf2[crimedf2["Type"]=="Trespassing and Vagrancy"].reset_index(drop=True)
UnlawfulEntry = crimedf2[crimedf2["Type"]=="Unlawful Entry"].reset_index(drop=True)
Motor = crimedf2[crimedf2["Type"]=="Unlawful Use of Motor Vehicle"].reset_index(drop=True)
Weapons = crimedf2[crimedf2["Type"]=="Weapons Act Offences"].reset_index(drop=True)

In [9]:
Arson

    Type                Date  Postcode   longitude   latitude
0  Arson 2025-09-23 21:30:00      4116  153.069117 -27.631002
1  Arson 2025-09-27 10:42:00      4110  153.029739 -27.604131
2  Arson 2025-09-28 03:46:00      4179  153.186378 -27.457121
3  Arson 2025-09-28 22:20:00      4110  153.027571 -27.607543

In [10]:
#Choose a desired width and height for your box: This will determine how far north, south, east, and west the box extends from the center point. For example, to get a box that is 0.1° in each direction from the center:

# North boundary: 27.479° S - 0.1° = 27.379° S
#   South boundary: 27.479° S + 0.1° = 27.579° S
#   West boundary: 153.023° E - 0.1° = 152.923° E
#   East boundary: 153.023° E + 0.1° = 153.123° E 

distance = 0.5

NBound = -27.479 - distance
SBound = -27.479 + distance
WBound = 153.023 - distance
EBound = 153.023 + distance

bbox = [NBound, SBound, WBound, EBound]

icon_names = ["beer","bug","leaf","car","gavel","home","car","legal","bomb","bomb","bomb","home","bomb","money","car","fire","home","bomb"]

In [11]:
m1 = leafmap.Map(center=(-27.4705, 153), zoom=11)
m1.add_points_from_xy(Stolen, x="longitude", y="latitude",color_column="Type")
m1

Map(center=[-27.4705, 153], controls=(ZoomControl(options=['position', 'zoom_in_text', 'zoom_in_title', 'zoom_…

In [12]:
m = leafmap.Map(center=(-27.4705, 153), zoom=11)
m.add_points_from_xy(crimedf2, x="longitude", y="latitude",icon_names=icon_names,color_column="Type")
m

The provided color string (lightred) is invalid. Using the default black color.
The provided color string (darkpurple) is invalid. Using the default black color.

Map(center=[-27.4705, 153], controls=(ZoomControl(options=['position', 'zoom_in_text', 'zoom_in_title', 'zoom_…

In [13]:
import leafmap.kepler as lkp

m = lkp.Map(center=(-27.4705, 153), zoom=11,height=800, width=1200)
m.add_data(data=crimedf2, name="Crime Data")
m

Map(config={'version': 'v1', 'config': {'mapState': {'latitude': -27.4705, 'longitude': 153, 'zoom': 11, 'bear…

In [16]:
import openpyxl
crimedf2.to_excel("output.xlsx")